### ISSUE TITLE
Using the scheduler to  run every day at midnight

### ISSUE THREAD

**Issue by Skyhikeeper** [georgemcz/SimpleScheduler#1]
Hi

How would you set the schedule action to run every day at midnight?

Terence

**Comment by georgemcz** [comment]
Hi,

sorry for late reply :)

from the top of my head, I'd write it like:


```
var taskM = Schedule.Action(() => Console.WriteLine("Midnight"))
                    .At(DateTime.Today + 1.day()) 
                    .ThenEvery(24.hours())
                    .InLocalTime()
                    .Start();
```

It says - At today - but that midnight has passed, so +1 day, then every 24 hours.
In local time shall compensate for DLT change shifting, so it shall execute in the local midnight and do not drift with DLT

Hope this helps

JM
