### ISSUE TITLE
Using the Abort Function 

### ISSUE THREAD

**Issue by Skyhikeeper** [georgemcz/SimpleScheduler#2]
I have started a schedule but want to kill it now how would you recommend doing this, as I cannot seem to get the abort function working.
This is the start  of the schedule
var FpsTimer = Schedule.Action(() => FpsTimer_Elapsed()).Every(1.sec()).InLocalTime().Start();

**Comment by georgemcz** [comment]
FpsTimer.Abort();

Is not working?

**Comment by Skyhikeeper** [comment]
No, the declaration is not a class declaration but within a method, even if i make the schedule global it still does not work.

**Comment by Skyhikeeper** [comment]
Do you have a working sample of using the scheduler

**Comment by georgemcz** [comment]
Not sure whether i understand where the problem is.

Abort is an extension method callable on the scheduled workitem instance- in your case the FpsTimer.

If you lose this reference, there’s no way how to abort it.

You need to store it in a field (for example) and then you can call Abort on that

Or, can you be more specific what’s wrong?

**Comment by georgemcz** [comment]
so for your issue, assuming following

```
var FpsTimer = Schedule.Action(() => FpsTimer_Elapsed()).Every(1.sec()).InLocalTime().Start();

// other code
FpsTimer.Abort();
```


for fields:

```
class XYZ
{
     private IWorkItem   _timer;

    void AnyMethod()
    {
        _timer = Schedule.Action(() => FpsTimer_Elapsed()).Every(1.sec()).InLocalTime().Start();
    }

    void OtherMethod()
    {
        _timer.Abort();
    }
}
```

Let me know whether this does help you

**Comment by Skyhikeeper** [comment]
Hi George

I have got it sorted out, was using the wrong object type instead of
iworkitem was using schedule.

Terence

**Comment by georgemcz** [comment]
Slightly updated the docu, to be more visible that the IWorkingItem shall be used.
Thank you for feedback
